<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="Approvebuisness.aspx.cs" Inherits="Approvebuisness" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

   
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT [Id], [businessname], [mechanicname], [services], [available], [address], [city], [locality], [mobile], [latitude], [longitude] FROM [createbusiness] where ([status]='Not Approved')" DeleteCommand="delete from createbusiness where Id=@Id">
        <DeleteParameters>
            <asp:Parameter Name="Id" />
        </DeleteParameters>
    </asp:SqlDataSource>
    <center><h1><b>Approve Business</b></h1></center>
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="Id" DataSourceID="SqlDataSource1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" Width="100%">
        <Columns>
            <asp:CommandField ShowSelectButton="True" />
            <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
            <asp:BoundField DataField="businessname" HeaderText="Business Name" SortExpression="businessname" />
            <asp:BoundField DataField="mechanicname" HeaderText="Mechanic Name" ReadOnly="True" SortExpression="mechanicname" />
            <asp:BoundField DataField="services" HeaderText="Services" SortExpression="services" />
            <asp:BoundField DataField="available" HeaderText="Available" SortExpression="available" />
            <asp:BoundField DataField="address" HeaderText="Address" SortExpression="address" />
            <asp:BoundField DataField="city" HeaderText="City" SortExpression="city" />
            <asp:BoundField DataField="locality" HeaderText="Locality" SortExpression="locality" />
            <asp:BoundField DataField="mobile" HeaderText="Mobile No" SortExpression="mobile" />
            <asp:BoundField DataField="latitude" HeaderText="Latitude" SortExpression="latitude" />
            <asp:BoundField DataField="longitude" HeaderText="Longitude" SortExpression="longitude" />
        </Columns>
        <FooterStyle BackColor="White" ForeColor="#000066" />
        <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
        <RowStyle ForeColor="#000066" />
        <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#007DBB" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#00547E" />
    </asp:GridView>
</asp:Content>

